version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
